NETWORK='%.%.%.%';

mysql -u rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY -p$MYSQL_rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY_PASSWORD --execute \
"CREATE USER IF NOT EXISTS 'rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY'@'${NETWORK}' IDENTIFIED BY '${MYSQL_rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'${NETWORK}' IDENTIFIED BY '${MYSQL_PASSWORD}';
CREATE USER IF NOT EXISTS 'dbviewer'@'${NETWORK}' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY'@'${NETWORK}';
GRANT SELECT, INSERT, UPDATE, DELETE ON railway.* TO 'root'@'${NETWORK}';
GRANT SELECT ON railway.* TO 'dbviewer'@'${NETWORK}';
DROP USER IF EXISTS 'rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY'@'%';
DROP USER IF EXISTS 'root'@'%';"
