services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./cfg/php.production.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_HOST: yamabiko.proxy.rlwy.net
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY
      STAGE: production
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Optional: phpMyAdmin to manage Railway database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8889:80"
    environment:
      PMA_HOST: yamabiko.proxy.rlwy.net
      PMA_USER: root
      PMA_PASSWORD: rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY
      PMA_PORT: 3306

# No local database needed - using Railway's database
# No networks needed for external database
# No volumes needed for external database