CREATE DATABASE IF NOT EXISTS railway;
USE railway;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'regmon123';
GRANT ALL PRIVILEGES ON railway.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON railway.* TO 'rgikBOGeTxNzMAcrsrFnIQzQaNXenZTY'@'%';
FLUSH PRIVILEGES;
